### ISSUE TITLE
config variable or hard coded

### ISSUE THREAD

**Issue by LeonSchourek** [byme8/ZeroQL#113]
**Is your feature request related to a problem? Please describe.**
the api that i use cant do variables so i need to use hardcoded values only

**Describe the solution you'd like**
send the values in query not in values

**Comment by byme8** [comment]
Firstly, using variables is part of the official GraphQL specification. In your case, it seems to be a server-side limitation rather than an issue with the GraphQL client library.

The current ZeroQL pipeline relies on query compilation during the build process. Implementing support for sending values directly in the query would require a significant overhaul of the library and its internal workflow.

Considering these factors, it is unlikely that this feature will be implemented in the foreseeable future.
