### ISSUE TITLE
Support for custom scalars

### ISSUE THREAD

**Issue by ahanoff** [byme8/ZeroQL#9]
>   GraphQL.g.cs(6110, 36): [CS0246] The type or namespace name 'ObjectId' could not be found (are you missing a using directive or an assembly reference?)

in schema it looks like:

```graphql
scalar ObjectId
```

Does it support custom scalars? I've generated client from schema that uses Mongo ObjectId, and got this error

**Comment by byme8** [comment]
At the moment, there is not support for custom scalar types. I will have a look at it.

**Comment by ahanoff** [comment]
> https://chillicream.com/docs/strawberryshake/scalars/#custom-scalars
By default, all custom scalars are treated like the String scalar. This means, that the client expects a string value and will deserialize it to a System.String.

thanks @byme8, btw this is how Strawberry Shake client treats custom scalars. Maybe it gives you some ideas

**Comment by byme8** [comment]
@ahanoff Checkout [v2.1.0](https://github.com/byme8/ZeroQL/releases/tag/v2.1.0)

**Comment by DaveRMaltby** [comment]
Should a schema that contains a TimeSpan start failing after upgrading to [v2.1.0](https://github.com/byme8/ZeroQL/releases/tag/v2.1.0)?  I am going to try to follow your readme and make a custom scalar for `System.TimeSpan`  If this works, I would like to create an issue for it and suggest that it be natively supported by ZeroQL.

**Comment by byme8** [comment]
At the moment, it will fail, because it is not bootstrapped properly in the library. It is possible to define it as a custom scalar, but it would be much better to handle it as a system type.

I already started working on it and noticed that HotChocolate and System.Text.Json serialize `` System.Text.Json `` in different formats. So, I am planning to add a more robust way to tinker with JSON serialization in the library.

**Comment by DaveRMaltby** [comment]
You rock!  Thanks.

**Comment by DaveRMaltby** [comment]
@byme8, great!  Thank you sir.  I'll take advantage of it.
